/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    HeadlLght: THREE.Mesh
    Wheels_1: THREE.Mesh
    Wheels_2: THREE.Mesh
    Wheels_3: THREE.Mesh
    Wheels_4: THREE.Mesh
    Object_57: THREE.Mesh
    Object_57_1: THREE.Mesh
    Object_57_2: THREE.Mesh
    Object_57_3: THREE.Mesh
    Object_57_4: THREE.Mesh
    Object_57_5: THREE.Mesh
    Object_57_6: THREE.Mesh
    Object_57_7: THREE.Mesh
    Object_57_8: THREE.Mesh
    Object_57_9: THREE.Mesh
    Object_57_10: THREE.Mesh
    Object_57_11: THREE.Mesh
    Object_57_12: THREE.Mesh
    Object_57_13: THREE.Mesh
    Object_57_14: THREE.Mesh
    Object_57_15: THREE.Mesh
    Object_57_16: THREE.Mesh
    Object_57_17: THREE.Mesh
    Object_57_18: THREE.Mesh
    Object_57_19: THREE.Mesh
    Object_57_20: THREE.Mesh
    Object_57_21: THREE.Mesh
    Object_57_22: THREE.Mesh
    Object_57_23: THREE.Mesh
    Plate: THREE.Mesh
    Engine: THREE.Mesh
  }
  materials: {
    emit: THREE.MeshStandardMaterial
    metalblack: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    sidetyre: THREE.MeshStandardMaterial
    main: THREE.MeshStandardMaterial
    bBMW_M4CompetitionG82TNR0_2021PaintTNR_Material_004: THREE.MeshStandardMaterial
    bBMW_M4CompetitionG82TNR0_2021GrilleNoAlpha5A_Material1: THREE.MeshStandardMaterial
    bBMW_M4CompetitionG82TNR0_2021GrilleNoAlpha6A_Material1: THREE.MeshStandardMaterial
    bBMW_M4CompetitionG82TNR0_2021GrilleNoAlpha7A_Material1: THREE.MeshStandardMaterial
    bBMW_M4CompetitionG82TNR0_2021GrilleNoAlpha8A_Material1: THREE.MeshStandardMaterial
    bBMW_M4CompetitionG82TNR0_2021GrilleNoAlpha9A_Material1: THREE.MeshStandardMaterial
    bBMW_M4CompetitionG82TNR0_2021Coloured_Material_004: THREE.MeshStandardMaterial
    bBMW_M4CompetitionG82TNR0_2021InteriorA_Material1: THREE.MeshStandardMaterial
    phong2: THREE.MeshStandardMaterial
    bBMW_M4CompetitionG82TNR0_2021BadgeA_Material1: THREE.MeshStandardMaterial
    dark: THREE.MeshStandardMaterial
    bBMW_M4CompetitionG82TNR0_2021Carbon1_Material1: THREE.MeshStandardMaterial
    bBMW_M4CompetitionG82TNR0_2021LightA_Material1: THREE.MeshStandardMaterial
    bBMW_M4CompetitionG82TNR0_2021ManufacturerPlateA_Material1: THREE.MeshStandardMaterial
    ['bBMW_M4CompetitionG82TNR0_2021Base_Material1.001']: THREE.MeshStandardMaterial
    glasswindshiled: THREE.MeshStandardMaterial
    red_glass: THREE.MeshStandardMaterial
    ['disk.001']: THREE.MeshStandardMaterial
    glass: THREE.MeshStandardMaterial
    wmit_red: THREE.MeshStandardMaterial
    bBMW_M4CompetitionG82TNR0_2021Base_Material1: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    bBMW_M4CompetitionG82TNR0_2021EngineA_Material1: THREE.MeshStandardMaterial
  }
}

export function Car(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/bmw_carbon_optimized.glb',
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name='Scene'>
        <mesh
          name='HeadlLght'
          castShadow
          receiveShadow
          geometry={nodes.HeadlLght.geometry}
          material={materials.emit}
          position={[0, 0.446, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.822}
        />
        <group name='Wheels'>
          <mesh
            name='Wheels_1'
            castShadow
            receiveShadow
            geometry={nodes.Wheels_1.geometry}
            material={materials.metalblack}
          />
          <mesh
            name='Wheels_2'
            castShadow
            receiveShadow
            geometry={nodes.Wheels_2.geometry}
            material={materials['Material.001']}
          />
          <mesh
            name='Wheels_3'
            castShadow
            receiveShadow
            geometry={nodes.Wheels_3.geometry}
            material={materials.sidetyre}
          />
          <mesh
            name='Wheels_4'
            castShadow
            receiveShadow
            geometry={nodes.Wheels_4.geometry}
            material={materials.main}
          />
        </group>
        <group name='Others' position={[0, 0.424, 0]}>
          <mesh
            name='Object_57'
            castShadow
            receiveShadow
            geometry={nodes.Object_57.geometry}
            material={
              materials.bBMW_M4CompetitionG82TNR0_2021PaintTNR_Material_004
            }
          />
          <mesh
            name='Object_57_1'
            castShadow
            receiveShadow
            geometry={nodes.Object_57_1.geometry}
            material={
              materials.bBMW_M4CompetitionG82TNR0_2021GrilleNoAlpha5A_Material1
            }
          />
          <mesh
            name='Object_57_2'
            castShadow
            receiveShadow
            geometry={nodes.Object_57_2.geometry}
            material={
              materials.bBMW_M4CompetitionG82TNR0_2021GrilleNoAlpha6A_Material1
            }
          />
          <mesh
            name='Object_57_3'
            castShadow
            receiveShadow
            geometry={nodes.Object_57_3.geometry}
            material={
              materials.bBMW_M4CompetitionG82TNR0_2021GrilleNoAlpha7A_Material1
            }
          />
          <mesh
            name='Object_57_4'
            castShadow
            receiveShadow
            geometry={nodes.Object_57_4.geometry}
            material={
              materials.bBMW_M4CompetitionG82TNR0_2021GrilleNoAlpha8A_Material1
            }
          />
          <mesh
            name='Object_57_5'
            castShadow
            receiveShadow
            geometry={nodes.Object_57_5.geometry}
            material={
              materials.bBMW_M4CompetitionG82TNR0_2021GrilleNoAlpha9A_Material1
            }
          />
          <mesh
            name='Object_57_6'
            castShadow
            receiveShadow
            geometry={nodes.Object_57_6.geometry}
            material={
              materials.bBMW_M4CompetitionG82TNR0_2021Coloured_Material_004
            }
          />
          <mesh
            name='Object_57_7'
            castShadow
            receiveShadow
            geometry={nodes.Object_57_7.geometry}
            material={
              materials.bBMW_M4CompetitionG82TNR0_2021InteriorA_Material1
            }
          />
          <mesh
            name='Object_57_8'
            castShadow
            receiveShadow
            geometry={nodes.Object_57_8.geometry}
            material={materials.phong2}
          />
          <mesh
            name='Object_57_9'
            castShadow
            receiveShadow
            geometry={nodes.Object_57_9.geometry}
            material={materials.bBMW_M4CompetitionG82TNR0_2021BadgeA_Material1}
          />
          <mesh
            name='Object_57_10'
            castShadow
            receiveShadow
            geometry={nodes.Object_57_10.geometry}
            material={materials.dark}
          />
          <mesh
            name='Object_57_11'
            castShadow
            receiveShadow
            geometry={nodes.Object_57_11.geometry}
            material={materials.bBMW_M4CompetitionG82TNR0_2021Carbon1_Material1}
          />
          <mesh
            name='Object_57_12'
            castShadow
            receiveShadow
            geometry={nodes.Object_57_12.geometry}
            material={materials.bBMW_M4CompetitionG82TNR0_2021LightA_Material1}
          />
          <mesh
            name='Object_57_13'
            castShadow
            receiveShadow
            geometry={nodes.Object_57_13.geometry}
            material={
              materials.bBMW_M4CompetitionG82TNR0_2021ManufacturerPlateA_Material1
            }
          />
          <mesh
            name='Object_57_14'
            castShadow
            receiveShadow
            geometry={nodes.Object_57_14.geometry}
            material={
              materials['bBMW_M4CompetitionG82TNR0_2021Base_Material1.001']
            }
          />
          <mesh
            name='Object_57_15'
            castShadow
            receiveShadow
            geometry={nodes.Object_57_15.geometry}
            material={materials.glasswindshiled}
          />
          <mesh
            name='Object_57_16'
            castShadow
            receiveShadow
            geometry={nodes.Object_57_16.geometry}
            material={materials.red_glass}
          />
          <mesh
            name='Object_57_17'
            castShadow
            receiveShadow
            geometry={nodes.Object_57_17.geometry}
            material={materials['Material.001']}
          />
          <mesh
            name='Object_57_18'
            castShadow
            receiveShadow
            geometry={nodes.Object_57_18.geometry}
            material={materials['disk.001']}
          />
          <mesh
            name='Object_57_19'
            castShadow
            receiveShadow
            geometry={nodes.Object_57_19.geometry}
            material={materials.metalblack}
          />
          <mesh
            name='Object_57_20'
            castShadow
            receiveShadow
            geometry={nodes.Object_57_20.geometry}
            material={materials.glass}
          />
          <mesh
            name='Object_57_21'
            castShadow
            receiveShadow
            geometry={nodes.Object_57_21.geometry}
            material={materials.wmit_red}
          />
          <mesh
            name='Object_57_22'
            castShadow
            receiveShadow
            geometry={nodes.Object_57_22.geometry}
            material={materials.bBMW_M4CompetitionG82TNR0_2021Base_Material1}
          />
          <mesh
            name='Object_57_23'
            castShadow
            receiveShadow
            geometry={nodes.Object_57_23.geometry}
            material={materials['Material.002']}
          />
        </group>
        <mesh
          name='Plate'
          castShadow
          receiveShadow
          geometry={nodes.Plate.geometry}
          material={materials['Material.003']}
        />
        <mesh
          name='Engine'
          castShadow
          receiveShadow
          geometry={nodes.Engine.geometry}
          material={materials.bBMW_M4CompetitionG82TNR0_2021EngineA_Material1}
          position={[0, 0.444, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.822}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/bmw_carbon_optimized.glb')
